added getEjectCommand
Programming-TRIGON/RobotCodeOffSeason2024 pull request #13
Opened 2024-08-22 16:08 UTC by Nummun14

2024-08-22 16:10 UTC, Strflightmight09 approved these changes

2024-08-22 17:45 UTC, levyishai requested changes
1. The way you use the command is wrong; you're calling `INTAKE.getSetTargetStateCommand`, and instead of returning that command, you're returning an instant command that gets that command. 
2. If you have a command without group logic or that is only a getter that accepts parameters, put it in CommandConstants as a constant command.

2024-08-25 11:29 UTC, levyishai requested changes
Bind the command to a button

2024-08-27 08:53 UTC, levyishai approved these changes

2024-08-28 13:15 UTC, merged