Move ShootingCalculations
Programming-TRIGON/RobotCodeOffSeason2024 pull request #14
Opened 2024-08-24 22:07 UTC by Strflightmight09

2024-08-25 19:15 UTC, levyishai requested changes
Replace all the Math.pow in the shooting calcs to x*x and make sure to rumble only when interrupted

2024-08-27 08:53 UTC, levyishai requested changes

2024-08-27 08:53 UTC, levyishai commented on src/main/java/frc/trigon/robot/misc/ShootingCalculations.java
> +        final double velocity4thPower = noteTangentialVelocity * noteTangentialVelocity * noteTangentialVelocity * noteTangentialVelocity;
multiply the velocity squared by itself

2024-08-27 08:53 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberConstants.java
> +                    "LeftClimberVisualization",
just call these RightClimber and LeftClimber

2024-08-27 08:53 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberVisualization.java
> +                        - stringLength * stringLength;
I would put correct brackets for more readability

2024-08-27 08:53 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/intake/IntakeCommands.java
> +                                RobotContainer.INTAKE.indicateCollection();
if it wasn't interrupted (it ended by isFinished) we'll want to indicate.

2024-08-29 15:25 UTC, levyishai approved these changes

2024-08-29 16:03 UTC, Nummun14 approved these changes

2024-08-29 16:04 UTC, merged