Climb Command
Programming-TRIGON/RobotCodeOffSeason2024 pull request #17
Opened 2024-08-27 08:26 UTC by Nummun14

2024-08-27 08:38 UTC, levyishai requested changes
Is this fully tested in sim?

2024-08-27 08:38 UTC, levyishai commented on src/main/java/frc/trigon/robot/constants/CommandConstants.java
> +    public static boolean IS_CLIMBING = false;
Why do you need this? (There is a reason that you did not implement. Make sure to know exactly why you have each piece of code you're writing. Or maybe make sure to code the command first by yourself, and then see what we had last year.)

2024-08-29 09:37 UTC, Nummun14 commented
> Is this fully tested in sim?

No, since the merge climber isn't working.

2024-08-29 09:38 UTC, levyishai commented
> No, since the merge climber isn't working.

Merge climber?

2024-08-29 09:40 UTC, Nummun14 commented
> > No, since the merge climber isn't working.
> 
> Merge climber?

since the merge**,** climber isn't working

2024-08-29 10:18 UTC, Nummun14 commented on src/main/java/frc/trigon/robot/commands/Commands.java
> +                ClimberCommands.getSetTargetStateCommand(ClimberConstants.ClimberState.PREPARE_FOR_CLIMB).until(OperatorConstants.CONTINUE_TRIGGER),
@levyishai maybe I could have it be until it reaches the target state instead of until the trigger?

2024-08-29 14:21 UTC, Strflightmight09 requested changes

2024-08-29 14:21 UTC, Strflightmight09 commented on src/main/java/frc/trigon/robot/commands/Commands.java
> +                ClimberCommands.getSetTargetStateCommand(ClimberConstants.ClimberState.PREPARE_FOR_CLIMB).until(() -> OperatorConstants.CONTINUE_TRIGGER.getAsBoolean() && RobotContainer.CLIMBER.atTar
Use the `runWhenContinueTriggerPressed` command. You can find it in the Shooter Command PR

2024-08-29 14:21 UTC, Strflightmight09 commented on src/main/java/frc/trigon/robot/constants/CommandConstants.java
> +            MOVE_CLIMBER_UP_MANUALLY_COMMAND = ClimberCommands.getSetTargetVoltageCommand(4),
The voltage should be a constant in `ClimberConstants`

2024-09-01 11:35 UTC, levyishai requested changes

2024-09-01 11:35 UTC, levyishai commented on src/main/java/frc/trigon/robot/constants/CommandConstants.java
> +    public static boolean IS_CLIMBING = false;
Where and why is this used?

2024-09-01 11:35 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/Commands.java
> +        return new SequentialCommandGroup(
The normal commands should be above all the utils.

2024-09-01 11:35 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/Commands.java
Change name and path

2024-09-01 11:35 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/Commands.java
> +                runWhenContinueTriggerPressed(ClimberCommands.getSetTargetStateCommand(ClimberConstants.ClimberState.CLIMB))
The logic here is flawed. This is why I want to see a full climb sequence- proof of concept.

2024-09-03 14:24 UTC, Strflightmight09 approved these changes

2024-09-03 14:38 UTC, levyishai requested changes
Add position resetting limit switch logic, like ezra did.

2024-09-03 14:38 UTC, levyishai commented on src/main/java/frc/trigon/robot/RobotContainer.java
> +        OperatorConstants.MOVE_CLIMBER_UP_MANUALLY_TRIGGER.whileTrue(CommandConstants.MOVE_CLIMBER_UP_MANUALLY_COMMAND.alongWith(new InstantCommand(() -> CommandConstants.IS_CLIMBING = true)));
The `alongWith` should be in the constants

2024-09-03 14:38 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberCommands.java
> +        return new InstantCommand(
this should be startend so it doesn't end instantly

2024-09-03 16:37 UTC, Strflightmight09 requested changes

2024-09-03 16:37 UTC, Strflightmight09 commented on src/main/java/frc/trigon/robot/RobotContainer.java
> +        configureSysIdBindings(CLIMBER);
Remove this

2024-09-03 16:37 UTC, Strflightmight09 commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberConstants.java
> +            GROUNDED_P = RobotHardwareStats.isSimulation() ? 0 : 0,
Calibrate a P value

2024-09-03 16:37 UTC, Strflightmight09 commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberConstants.java
> +            ON_CHAIN_P = RobotHardwareStats.isSimulation() ? 0 : 0,
Calibrate a P value

2024-09-03 17:29 UTC, Strflightmight09 approved these changes

2024-09-03 18:30 UTC, levyishai requested changes

2024-09-03 18:30 UTC, levyishai commented on build.gradle
> +    implementation 'com.github.Programming-TRIGON:TRIGONLib:2024.2.6'
update from main

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/RobotContainer.java
> +        OperatorConstants.OVERRIDE_IS_CLIMBING_TRIGGER.onTrue(CommandConstants.OVERRIDE_IS_CLIMBING_COMMAND);
put the climb stuff next to each other

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/CommandConstants.java
> +    public static boolean IS_CLIMBING = false;
Now that I think about it, this should be a variable in the climber (with a setter / getter)

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/Climber.java
> +        positionResettingTrigger.onTrue(new InstantCommand(() -> motor.setPosition(ClimberConstants.LIMIT_SWITCH_PRESSED_POSITION)));
this command should run when disabled

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberConstants.java
> +            MAX_ON_CHAIN_ACCELERATION = RobotHardwareStats.isSimulation() ? (12 / ON_CHAIN_KA) - 40 : 0;
check these numbers

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/ClimberConstants.java
> +        motor.registerSignal(TalonFXSignal.FORWARD_LIMIT, 100);
there is not forward limit, don't register it.

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/swerve/SwerveModule.java
update from main

2024-09-03 18:30 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/swerve/SwerveConstants.java
update from main

2024-09-03 19:22 UTC, Strflightmight09 approved these changes

2024-09-03 21:39 UTC, levyishai approved these changes

2024-09-04 04:42 UTC, merged