Climber Logic Fixes
Programming-TRIGON/RobotCodeOffSeason2024 pull request #31
Opened 2024-09-30 09:10 UTC by Nummun14

2024-09-30 09:11 UTC, Strflightmight09 approved these changes

2024-09-30 23:04 UTC, levyishai requested changes

2024-09-30 23:04 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/climber/Climber.java
Make the default command braking

2024-10-01 11:37 UTC, Nummun14 commented on src/main/java/frc/trigon/robot/subsystems/climber/Climber.java
I don't understand what you mean, The climber is already set to brake by default. What do I need to change?

2024-10-01 12:47 UTC, levyishai approved these changes

2024-10-01 14:06 UTC, merged