Gear Ratio Calculator
Programming-TRIGON/RobotCodeOffSeason2024 pull request #32
Opened 2024-10-01 11:43 UTC by Strflightmight09

2024-10-01 12:40 UTC, levyishai requested changes

2024-10-01 12:40 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/GearRatioCalculationCommand.java
> +
Extra newline

2024-10-01 12:40 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/GearRatioCalculationCommand.java
> +    public GearRatioCalculationCommand(Supplier<Rotation2d> rotorPositionSupplier, Supplier<Rotation2d> encoderPositionSupplier, DoubleConsumer runGearRatioCalculation, SubsystemBase requirement) {
This isn't always a rotation2d 
It can be unitless

2024-10-01 12:40 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/GearRatioCalculationCommand.java
> +    private void printResults() {
Results plural?

2024-10-01 13:00 UTC, levyishai requested changes

2024-10-01 13:00 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/pitcher/PitcherCommands.java
> +                () -> RobotContainer.PITCHER.getCurrentPitch().getDegrees(),
Get current pitch will not return the rotor position, you have a remote encoder configured onto the falcon..

2024-10-01 13:00 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/GearRatioCalculationCommand.java
> +public class GearRatioCalculationCommand extends Command {
Looks good, move to lib

2024-10-01 15:15 UTC, levyishai approved these changes

2024-10-02 12:21 UTC, levyishai requested changes

2024-10-02 12:21 UTC, levyishai commented on src/main/java/frc/trigon/robot/subsystems/pitcher/Pitcher.java
> +    }
why not just use `drive`?

2024-10-06 09:16 UTC, levyishai approved these changes

2024-10-06 14:04 UTC, Nummun14 approved these changes

2024-10-06 15:28 UTC, merged