Vision Fixes
Programming-TRIGON/RobotCodeOffSeason2024 pull request #33
Opened 2024-10-05 17:10 UTC by Strflightmight09

2024-10-05 19:13 UTC, levyishai requested changes

2024-10-05 19:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/constants/CameraConstants.java
> +            THETA_STD_EXPONENT = 0.01;
these should be passed in the constructor

2024-10-05 19:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> +        if (!inputs.hasResult || inputs.distanceFromBestTag == 0 || robotPose == null)
why check this twice?

2024-10-05 19:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> -    }
implement this somewhere, probably pose estimator (obviously not as simple as copy paste, you should reset to the camera with the smallest distance from best tag)

2024-10-06 00:09 UTC, levyishai requested changes
Instead of tossing an error down the drain every time I see it in hopes it'll fix itself, I've found the problem that was crashing the code: `AprilTagPhotonCameraIO.java:99`

2024-10-06 17:19 UTC, levyishai requested changes

2024-10-06 17:19 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> +        if (!inputs.hasResult || inputs.distanceFromBestTag == 0 || robotPose == null)
This `if` should really happen once

2024-10-06 17:19 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/poseestimator/PoseEstimator.java
> +        final Rotation2d bestRobotHeading = aprilTagCameras[closestCameraToTag].getEstimatedRobotPose().getRotation();
This isn't necessarily solvepnp

2024-10-06 17:31 UTC, levyishai requested changes

2024-10-06 17:31 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> +            Logger.recordOutput("Poses/Robot/" + name + "Pose", robotPose);
the robotPose == null can be in the other if
Add a slash after name

2024-10-06 17:31 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> +    }
Add  a slash after name

2024-10-06 17:31 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> +            Logger.recordOutput("Poses/Robot/" + name + "SolvePNPPose", AprilTagCameraConstants.EMPTY_POSE_LIST);
Add a slash after name

2024-10-06 17:32 UTC, levyishai requested changes

2024-10-06 17:32 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/apriltagcamera/AprilTagCamera.java
> +    }
will this return correctly?

2024-10-06 17:32 UTC, levyishai commented on src/main/java/frc/trigon/robot/poseestimation/poseestimator/PoseEstimator.java
> +
implement this button

2024-10-06 17:43 UTC, levyishai requested changes

2024-10-06 17:43 UTC, levyishai commented on src/main/java/frc/trigon/robot/commands/CommandConstants.java
>              SELF_RELATIVE_DRIVE_FROM_DPAD_COMMAND = SwerveCommands.getClosedLoopSelfRelativeDriveCommand(
Run when disabled

2024-10-06 17:45 UTC, levyishai approved these changes

2024-10-06 17:53 UTC, Nummun14 approved these changes

2024-10-06 17:54 UTC, merged