Update README.md
Programming-TRIGON/RobotCodeOffSeason2024 pull request #36
Opened 2024-11-06 15:01 UTC by Strflightmight09

2024-11-06 15:05 UTC, Nummun14 approved these changes

2024-11-07 17:06 UTC, levyishai requested changes
Wrong link, should link to the TRIGON drive.

2024-11-11 09:29 UTC, Nummun14 approved these changes

2024-11-11 21:03 UTC, levyishai requested changes

2024-11-11 21:03 UTC, levyishai commented on README.md
> +found [here](https://drive.google.com/drive/folders/1mMYOdDzlApMwTz2Wo5Z5GBv4ffCnPAjh?usp=drive_link)
Layout name is still tragedy.
And I also just noticed there's no comma in the end of the sentence here.

2024-11-12 11:02 UTC, Nummun14 requested changes

2024-11-12 11:02 UTC, Nummun14 commented on README.md
> +found [here](https://drive.google.com/drive/folders/1mMYOdDzlApMwTz2Wo5Z5GBv4ffCnPAjh?usp=drive_link).
![image](https://github.com/user-attachments/assets/8f8fdffa-04b3-42bf-adc9-383b02ca5f2c)
it still says Tragedy in the layout :)

2024-11-13 17:51 UTC, Nummun14 commented on README.md
> +found [here](https://drive.google.com/drive/folders/1mMYOdDzlApMwTz2Wo5Z5GBv4ffCnPAjh?usp=drive_link).
The name is still tragedy I'm the config file :)

2024-11-13 17:53 UTC, Nummun14 requested changes

2024-11-13 17:53 UTC, Nummun14 commented on README.md
> +found [here](https://drive.google.com/drive/folders/1mMYOdDzlApMwTz2Wo5Z5GBv4ffCnPAjh?usp=drive_link).
The name of still tragedy in the config file :)

2024-11-14 12:30 UTC, Nummun14 approved these changes

2024-11-14 13:32 UTC, levyishai approved these changes

2024-11-14 13:40 UTC, merged