Create README.md
Programming-TRIGON/RobotCodeOffSeason2024 pull request #4
Opened 2024-08-04 12:44 UTC by Strflightmight09

2024-08-04 13:13 UTC, levyishai requested changes
Mention the TRIGONLib

2024-08-04 14:08 UTC, levyishai requested changes

2024-08-04 14:08 UTC, levyishai commented on README.md
> +# TrigonLIB
TRIGONLib

2024-08-04 14:08 UTC, levyishai commented on README.md
> +[![](https://jitpack.io/v/Programming-TRIGON/TRIGONLib.svg)](https://jitpack.io/#Programming-TRIGON/TRIGONLib)
Place the Jitpack link in the the title

2024-08-04 14:08 UTC, levyishai commented on README.md
> +TRIGON 5990's library for hardware wrappers, utilities, commands, etc.
```suggestion

[TRIGON 5990's library](https://github.com/Programming-TRIGON/TRIGONLib) for automatic Advantage Kit and Simulation hardware wrappers, utilities, commands, and more.
```

2024-08-04 14:09 UTC, levyishai reviewed
@Nummun14 feel free to leave a review as well

2024-08-04 20:15 UTC, Strflightmight09 commented on README.md
> +[![](https://jitpack.io/v/Programming-TRIGON/TRIGONLib.svg)](https://jitpack.io/#Programming-TRIGON/TRIGONLib)
Where exactly do you want me to put it?

2024-08-04 20:16 UTC, levyishai commented on README.md
> +[![](https://jitpack.io/v/Programming-TRIGON/TRIGONLib.svg)](https://jitpack.io/#Programming-TRIGON/TRIGONLib)
Next to the `# TRIGONLib `

2024-08-05 09:48 UTC, levyishai approved these changes

2024-08-05 10:37 UTC, Nummun14 approved these changes

2024-08-05 11:10 UTC, merged